version: '3.8'
services:
  database:
    container_name: attention-spanner-postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
       POSTGRES_USER: postgres
       POSTGRES_DB: attention-spanner-postgres
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  server:
    container_name: attention-spanner
    image: attention-spanner:latest
#    env_file:
#      .env
    build:
      context: .
#      dockerfile: Dockerfile
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8080:8080"
volumes:
  data:
